name: morph
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - ffmpeg=4.1
  - freetype=2.9.1
  - gmp=6.1.2
  - gnutls=3.6.5
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.36
  - ncurses=6.1
  - nettle=3.4.1
  - openh264=1.8.0
  - openssl=1.1.1a
  - pip=19.0.1
  - python=3.7.2
  - readline=7.0
  - setuptools=40.7.3
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - x264=1!152.20180717
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - gym==0.11.0
    - imageio==2.5.0
    - ipyvolume==0.5.2
    - ipycanvas==0.2.2
    - ipykernel==5.1.2
    - ipympl==0.2.1
    - ipython==7.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - joblib==0.13.1
    - jsonschema==2.6.0
    - jupyter>=1.0.0
    - kiwisolver==1.0.1
    - lockfile==0.12.2
    - markupsafe==1.1.1
    - matplotlib==3.0.2
    - mistune==0.8.4
    - more-itertools==5.0.0
    - mpi4py==3.0.0
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - netifaces==0.10.9
    - networkx==2.2
    - notebook==5.7.8
    - numpy==1.16.1
    - nvidia-ml-py3==7.352.0
    - pandas==0.24.1
    - pandocfilters==1.4.2
    - parso==0.3.3
    - pathtools==0.1.2
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pillow==5.4.1
    - pluggy==0.8.1
    - prometheus-client==0.6.0
    - promise==2.2.1
    - prompt-toolkit==2.0.8
    - psutil==5.5.0
    - ptyprocess==0.6.0
    - pyglet==1.3.2
    - pygments==2.3.1
    - pyopengl==3.1.0
    - pyparsing==2.3.1
    - pytest==4.2.0
    - python-dateutil==2.8.0
    - pytz==2018.9
    - pywavelets==1.0.2
    - pyyaml==5.1
    - pyzmq==18.0.0
    - scikit-image==0.14.2
    - scipy==1.2.0
    - seaborn==0.9.0
    - shortuuid==0.5.0
    - six==1.12.0
    - subprocess32==3.5.3
    - terminado==0.8.2
    - testpath==0.4.2
    - toolz==0.9.0
    - torch==1.1.0
    - torchsummary==1.5.1
    - torchvision==0.2.1
    - torchviz==0.0.1
    - tornado==6.0
    - tqdm==4.30.0
    - urllib3==1.24.1
    - wandb==0.8.10